Token=90091783788801371:0:GgdxnYSxGTIZiz85z1C6z4iuGc05O8
URI=wss://d1.nandbox.net:5020/nandbox/api/
DownloadServer=https://d1.nandbox.net:5020/nandbox/download/
UploadServer=https://d1.nandbox.net:5020/nandbox/upload/