name: CI

on:
  push:
    branches: [main]

jobs:
  sync:
    uses: nandbox-bot/shared-ci/.github/workflows/build-ghcr.yml@main
    secrets:
      ORG_PAT: ${{ secrets.ORG_PAT }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_SECRET }}
